### ISSUE TITLE
Release/Tag on github

### ISSUE THREAD

**Issue by hanslovsky** [scijava/jgo#18]
Currently, I have jrun on my conda channel but I think it would make a lot of sense to add it to the conda-forge channel. For that it would be nice to have a release/tag. Any objections against a 0.1.0 release?

**Comment by ctrueden** [comment]
Sure, let's do it. And let's move this repository to the scijava org now, since it is not only my personal project anymore.

**Comment by hanslovsky** [comment]
We got a release now, so closing this.
