### ISSUE TITLE
Maven project directories/repositories as endpoints

### ISSUE THREAD

**Issue by hanslovsky** [scijava/jgo#35]
When testing applications in the development stage with jgo, I usually do this:
```sh
$ mvn clean install
$ jgo [JGO_ARG ...] <groupId>:<artifactId>:<version>-SNAPSHOT[:<mainClass> ] [PROGRAM_ARG ...]
```

Having paths to directories/urls to git urls as endpoints would be super useful to run snapshot versions (or releases that are not available on any maven repos) through jgo. I have no clear idea how to combine that with the existing endpoint syntax yet, but assuming that we we have a way of identifying such non-coordinate endpoints, we should check:
 - if non-coordinate endpoint is file path, use local maven project as endpoint if
    - path ends in `pom.xml`, or
    - path is directory and contains `pom.xml`
 - if non-coordinate endpoint is url, use remote maven project as endpoint if
   - url points to a git(hub) repository

`mvn clean install` would run 
  - automatically if the the jar is not available in the local maven repository, or
  - would be triggered by flag

git urls could have an optional commit/tag 

The syntax for running an application in development via jgo would simplify to:
```sh
$ jgo [JGO_ARG ...] .[:mainClass] [PROGRAM_ARG ...]
```
No risk of specifying wrong version.

**Comment by ctrueden** [comment]
I don't think jgo needs any additional features here.

If you build locally with `mvn install`, then jgo already works as is. If your goal is to avoid cloning and building locally, then try jitpack.io. It builds git repos automatically on demand and serves the results via Maven; should combo nicely with jgo.

**Comment by hanslovsky** [comment]
The point is not to avoid cloning and installing (that would just be a nice additional feature, though, and could be easily added) but to just have to run `jgo <path to maven project>`, e.g. `jgo .` inside a maven project. This is super useful to test if an application works outside the ide before committing/pushing.

**Comment by ctrueden** [comment]
You could accomplish that with an alias like:
```
alias jgolocal='echo "== Building project ==" && mvn -q install && echo "== Launching project ==" && jgo $(mvn -q -Dexec.executable=echo -Dexec.args='\''${project.groupId}:${project.artifactId}:${project.version}'\'' --non-recursive exec:exec)'
```
And then typing `jgolocal` would do `mvn install` followed by `jgo` on the installed GAV.

However, that feels convoluted to me. Why not simply run:
```
mvn -Pexec
```
This works well for local testing as long as you define a `main-class` property.

**Comment by hanslovsky** [comment]
I did not know about `mvn -Pexec`, thank you for pointing that out! That is obviously the most simple and best solution to my issue.
