### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by ctrueden** [scijava/jgo#44]
We can use [cram](https://bitheap.org/cram/). For all tests, run with both versions of jgo.

* Execute Parsington 1+3
* Shortcuts
* Main class abbreviations with `@`
* FQCN main class
* No main class
* Repeated execution of same endpoint
* Consistency of cache directory trees
* Various flags (`-u`, `-U`, `-m`, `-v`)

**Comment by jayvdb** [comment]
I am writing some tests atm, and would love to know a real use case for `--additional-endpoints` and `--additional-jars`. 

I noticed an issue where an additional jar was needed for Groovy, but it seems to not need it now as `PATH=/c/Program\ Files/Java/jdk-17.0.2/bin/:$PATH  jgo org.codehaus.groovy:groovy-groovysh:org.codehaus.groovy.tools.shell.Main` drops me into a Groovy prompt.

I see https://github.com/scijava/jgo/issues/43 deprecated `--additional-jars` three (3) years ago - I could just remove that CLI arg so it doesn't need tests.

**Comment by jayvdb** [comment]
The main set of code not covered in https://github.com/scijava/jgo/pull/79 was the `if main_class[0] == "@":` branch in `autocomplete_main_class`.  I couldnt quickly see how to trigger that.

**Comment by ctrueden** [comment]
I filed #86 to track the test reproducibility issue with unpinned versions. I am closing this issue, thanks to @jayvdb's nice work on #79. :beers:
