### ISSUE TITLE
Installation via conda leads to non-functional jgo

### ISSUE THREAD

**Issue by imagejan** [scijava/jgo#59]
On Windows (in MINGW64 via Git Bash), creating a new conda environment and installing `jgo-1.0.0` via `conda install jgo -c conda-forge` leads to a non-functional jgo installation.

After activating the environment, when running `jgo` I get the following error:

```
/c/anaconda383/x64/envs/jgo-test/Scripts/jgo: line 2: C:/anaconda383/x64/envs/jgo-test/bin/python: No such file or directory
```

The content of `/c/anaconda383/x64/envs/jgo-test/Scripts/jgo` is:

```
#!/bin/sh
'''exec' C:/anaconda383/x64/envs/jgo-test/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from jgo import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by ctrueden** [comment]
@imagejan Do you happen to know if 0.5.0 works? That release is identical to 1.0.0 functionally. So if 0.5.0 works but 1.0.0, that tells us something must have changed in the conda-forge infrastructure which results in this issue.

**Comment by imagejan** [comment]
Interestingly, `jgo-0.5.0` returns to the command prompt immediately (no help message, no error message), no matter if I provide an endpoint or not.

**Comment by hinerm** [comment]
on Windows using miniconda3:

* `conda install jgo -c conda-forge` works for me to install `jgo`
* I cannot use the `jgo` command-line script due to it being `sh`-style
* `python -c "import jgo; jgo.main()"` works for me. As does running from an interactive python.

**Comment by imagejan** [comment]
Indeed, `python -c "import jgo; jgo.main()"` works for me. It's just the command line script that is buggy when installed via conda, whereas it seems to work when installed via pip. (I'm using it from Git Bash.)

**Comment by ctrueden** [comment]
@hinerm wrote:
> I cannot use the jgo command-line script due to it being sh-style

I think there is a miscommunication here. The script `jgo.sh` is a completely separate thing, whereas @imagejan is talking about the command-line entry point into `jgo.main`. This entry point, which should be runnable with `jgo` even on Windows, should print something like:
```
$ which jgo
/usr/local/Caskroom/miniconda/base/envs/pyimagej-dev/bin/jgo
$ jgo
usage: jgo [-v] [-u] [-U] [-m] [-q] [--log-level] [--ignore-jgorc] [--link-type type] [--additional-jars jar [jar ...]] [--additional-endpoints endpoint [endpoint ...]] [JVM_OPTIONS [JVM_OPTIONS ...]] <endpoint> [main-args]
ERROR 2022-05-09 16:20:01,208: No endpoint provided. Run `jgo --help' for a detailed help message.
```

@imagejan @hinerm Does it still happen with jgo 1.0.4? And do you know if the `imagej` entry point from pyimagej works? If `imagej` works but `jgo` doesn't, we can change jgo to specify the main function in setup.py the same way pyimagej does it in its setup.cfg.

To debug this further, check out the `jgo` console script. Mine looks like this:
```
#!/bin/sh
'''exec' /usr/local/Caskroom/miniconda/base/envs/pyimagej-dev/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from jgo import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

If you strip take only the Python portion of that code and make a script out of it and run it with `python`, does that work? If so, maybe git bash on Windows behaves differentlyl with the exec hack at the top here? I'm curious whether `imagej` works; if it also doesn't, this may be a broader issue with console entry points and Windows.

**Comment by ctrueden** [comment]
OK, reading the error message above more carefully:
```
/c/anaconda383/x64/envs/jgo-test/Scripts/jgo: line 2: C:/anaconda383/x64/envs/jgo-test/bin/python: No such file or directory
```
It's path mangling. Git Bash related. I bet that `imagej` also doesn't work, nor do other console entry points. I am going to close this as "invalid" since it's not jgo-specific. @imagejan If other console entry points *do* work, then please reopen. Another avenue of inquiry here would be to check the script contents when installed via pip and see how it differs, since you said that works?
