### ISSUE TITLE
ETA for new release?

### ISSUE THREAD

**Issue by tferr** [scijava/jgo#85]
Hi guys, just a quick question:
Folks keep hitting the same issue reported here: https://github.com/imagej/pyimagej/issues/222. The [fix](https://github.com/scijava/jgo/commit/49aa492aa4718608d59f0cbc0d3d7810f6398a5b) is already in place. We were just wondering if there will be a new release soon, or if we should put in SNT's documentation that it is advisable to clone jgo locally.

**Comment by ctrueden** [comment]
I released jgo 1.0.5 to PyPI. Should propagate to conda-forge within a few hours. Thanks @tferr for the reminder!

**Comment by tferr** [comment]
Thanks a lot @ctrueden!

**Comment by carshadi** [comment]
thanks @ctrueden !!
