### ISSUE TITLE
Change the default cache directory

### ISSUE THREAD

**Issue by MosGeo** [scijava/jgo#96]
Currently jgo uses `~/.jgo` as the cache directory. It would be great if this folder location can be modified by the user through Python or through environmental variable.

## Rational
By letting the user define the folder location, portablity can be improved. For example, the cache directory can be moved easily with with the project to a new computer and it would just work without redownloading the required files or manually copying the `.jgo` folder to the user directory.

## Workaround
Write some code in python at the start of the application to copy .jgo folder if it is not found in the user directory. It is not ideal as it might conflict with exsiting folder. Also, it feels like a hack.

**Comment by jayvdb** [comment]
I believe it can be configured using env var `JGO_CACHE_DIR`

**Comment by ctrueden** [comment]
Yes, like @jayvdb said, `JGO_CACHE_DIR` should work; it's been part of jgo since at least 0.2.0.

@MosGeo But definitely please reopen this issue if it doesn't do the job for you!
